# Generated by Django 3.2.5 on 2021-07-31 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pacient",
            new_name="Patient",
        ),
    ]
